/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cw20HookMsg =
  | {
      increase_lockup: {
        duration: number;
        [k: string]: unknown;
      };
    }
  | {
      increase_apollo_incentives: {
        [k: string]: unknown;
      };
    }
  | {
      stake_astro_and_increase_lockup: {
        duration: number;
        [k: string]: unknown;
      };
    };
