/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateConfigMsg {
  /**
   * APOLLO Factory
   */
  apollo_factory?: string | null;
  /**
   * APOLLO Token
   */
  apollo_token?: string | null;
  astro_token?: string | null;
  astroport_staking?: string | null;
  /**
   * Number of seconds during which lockup deposits will be accepted
   */
  deposit_window?: number | null;
  /**
   * Timestamp when Contract will start accepting LP Token deposits
   */
  init_timestamp?: number | null;
  /**
   * Max. no. of weeks allowed for lockup
   */
  max_lock_duration?: number | null;
  /**
   * Max lockup positions a user can have
   */
  max_positions_per_user?: number | null;
  /**
   * Min. no. of weeks allowed for lockup
   */
  min_lock_duration?: number | null;
  /**
   * Account which can update config
   */
  owner?: string | null;
  /**
   * Withdrawal Window Length :: Post the deposit window
   */
  withdrawal_window?: number | null;
  /**
   * xASTRO token address
   */
  xastro_token?: string | null;
  [k: string]: unknown;
}
